# Generated by Django 4.2.25 on 2025-10-22 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('league', models.CharField(choices=[('liga_1', 'Liga 1'), ('liga_2', 'Liga 2'), ('n/a', 'Tidak Diketahui')], default='n/a', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('status_short', models.CharField(max_length=10)),
                ('status_long', models.CharField(max_length=50)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.venue')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_category', models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('REGULAR', 'Regular')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.PositiveIntegerField(default=0, help_text='Jumlah tiket yang tersedia untuk kategori ini')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='matches.match')),
            ],
            options={
                'unique_together': {('match', 'seat_category')},
            },
        ),
    ]
