# Generated by Django 5.2.7 on 2025-10-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_team_api_id_alter_team_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('liga_1', 'Liga 1'), ('liga_2', 'Liga 2'), ('n/a', 'Tidak Diketahui')], default='n/a', max_length=10),
        ),
    ]
