# Generated by Django 5.2.7 on 2025-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_away_goals_alter_match_home_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
