# Generated by Django 5.2.7 on 2025-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_venue_api_id_alter_match_away_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
