# Generated by Django 5.2.7 on 2025-10-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='royalty_poin',
        ),
    ]
