# Generated by Django 5.2.6 on 2025-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='midtrans_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
