# Generated by Django 5.2.7 on 2025-10-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_midtrans_order_id'),
        ('matches', '0004_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('CONFIRMED', 'Terkonfirmasi'), ('EXPIRED', 'Kadaluarsa')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('ticket_type', models.ForeignKey(choices=[('Regular', 'Regular'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], on_delete=django.db.models.deletion.PROTECT, to='matches.ticketprice')),
            ],
        ),
    ]
